// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Jets             string
	Languages        string
	PilotLanguages   string
	Pilots           string
	SchemaMigrations string
}{
	Jets:             "jets",
	Languages:        "languages",
	PilotLanguages:   "pilot_languages",
	Pilots:           "pilots",
	SchemaMigrations: "schema_migrations",
}
