// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testParhams(t *testing.T) {
	t.Parallel()

	query := Parhams()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testParhamsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Parham{}
	if err = randomize.Struct(seed, o, parhamDBTypes, true, parhamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Parham struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Parhams().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testParhamsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Parham{}
	if err = randomize.Struct(seed, o, parhamDBTypes, true, parhamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Parham struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Parhams().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Parhams().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testParhamsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Parham{}
	if err = randomize.Struct(seed, o, parhamDBTypes, true, parhamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Parham struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ParhamSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Parhams().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testParhamsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Parham{}
	if err = randomize.Struct(seed, o, parhamDBTypes, true, parhamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Parham struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ParhamExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Parham exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ParhamExists to return true, but got false.")
	}
}

func testParhamsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Parham{}
	if err = randomize.Struct(seed, o, parhamDBTypes, true, parhamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Parham struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	parhamFound, err := FindParham(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if parhamFound == nil {
		t.Error("want a record, got nil")
	}
}

func testParhamsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Parham{}
	if err = randomize.Struct(seed, o, parhamDBTypes, true, parhamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Parham struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Parhams().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testParhamsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Parham{}
	if err = randomize.Struct(seed, o, parhamDBTypes, true, parhamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Parham struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Parhams().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testParhamsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	parhamOne := &Parham{}
	parhamTwo := &Parham{}
	if err = randomize.Struct(seed, parhamOne, parhamDBTypes, false, parhamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Parham struct: %s", err)
	}
	if err = randomize.Struct(seed, parhamTwo, parhamDBTypes, false, parhamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Parham struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = parhamOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = parhamTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Parhams().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testParhamsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	parhamOne := &Parham{}
	parhamTwo := &Parham{}
	if err = randomize.Struct(seed, parhamOne, parhamDBTypes, false, parhamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Parham struct: %s", err)
	}
	if err = randomize.Struct(seed, parhamTwo, parhamDBTypes, false, parhamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Parham struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = parhamOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = parhamTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Parhams().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func parhamBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Parham) error {
	*o = Parham{}
	return nil
}

func parhamAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Parham) error {
	*o = Parham{}
	return nil
}

func parhamAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Parham) error {
	*o = Parham{}
	return nil
}

func parhamBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Parham) error {
	*o = Parham{}
	return nil
}

func parhamAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Parham) error {
	*o = Parham{}
	return nil
}

func parhamBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Parham) error {
	*o = Parham{}
	return nil
}

func parhamAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Parham) error {
	*o = Parham{}
	return nil
}

func parhamBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Parham) error {
	*o = Parham{}
	return nil
}

func parhamAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Parham) error {
	*o = Parham{}
	return nil
}

func testParhamsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Parham{}
	o := &Parham{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, parhamDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Parham object: %s", err)
	}

	AddParhamHook(boil.BeforeInsertHook, parhamBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	parhamBeforeInsertHooks = []ParhamHook{}

	AddParhamHook(boil.AfterInsertHook, parhamAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	parhamAfterInsertHooks = []ParhamHook{}

	AddParhamHook(boil.AfterSelectHook, parhamAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	parhamAfterSelectHooks = []ParhamHook{}

	AddParhamHook(boil.BeforeUpdateHook, parhamBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	parhamBeforeUpdateHooks = []ParhamHook{}

	AddParhamHook(boil.AfterUpdateHook, parhamAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	parhamAfterUpdateHooks = []ParhamHook{}

	AddParhamHook(boil.BeforeDeleteHook, parhamBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	parhamBeforeDeleteHooks = []ParhamHook{}

	AddParhamHook(boil.AfterDeleteHook, parhamAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	parhamAfterDeleteHooks = []ParhamHook{}

	AddParhamHook(boil.BeforeUpsertHook, parhamBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	parhamBeforeUpsertHooks = []ParhamHook{}

	AddParhamHook(boil.AfterUpsertHook, parhamAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	parhamAfterUpsertHooks = []ParhamHook{}
}

func testParhamsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Parham{}
	if err = randomize.Struct(seed, o, parhamDBTypes, true, parhamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Parham struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Parhams().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testParhamsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Parham{}
	if err = randomize.Struct(seed, o, parhamDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Parham struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(parhamColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Parhams().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testParhamsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Parham{}
	if err = randomize.Struct(seed, o, parhamDBTypes, true, parhamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Parham struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testParhamsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Parham{}
	if err = randomize.Struct(seed, o, parhamDBTypes, true, parhamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Parham struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ParhamSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testParhamsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Parham{}
	if err = randomize.Struct(seed, o, parhamDBTypes, true, parhamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Parham struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Parhams().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	parhamDBTypes = map[string]string{`ID`: `integer`, `Name`: `character varying`}
	_             = bytes.MinRead
)

func testParhamsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(parhamPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(parhamAllColumns) == len(parhamPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Parham{}
	if err = randomize.Struct(seed, o, parhamDBTypes, true, parhamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Parham struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Parhams().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, parhamDBTypes, true, parhamPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Parham struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testParhamsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(parhamAllColumns) == len(parhamPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Parham{}
	if err = randomize.Struct(seed, o, parhamDBTypes, true, parhamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Parham struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Parhams().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, parhamDBTypes, true, parhamPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Parham struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(parhamAllColumns, parhamPrimaryKeyColumns) {
		fields = parhamAllColumns
	} else {
		fields = strmangle.SetComplement(
			parhamAllColumns,
			parhamPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ParhamSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testParhamsUpsert(t *testing.T) {
	t.Parallel()

	if len(parhamAllColumns) == len(parhamPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Parham{}
	if err = randomize.Struct(seed, &o, parhamDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Parham struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Parham: %s", err)
	}

	count, err := Parhams().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, parhamDBTypes, false, parhamPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Parham struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Parham: %s", err)
	}

	count, err = Parhams().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
